[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_BASE = "https://teawebsite-f6328f6fe19f.herokuapp.com"
  NEXT_PUBLIC_USE_MOCK = "0"
  NEXT_PUBLIC_SITE_URL = "https://innerveda.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_BASE = "https://teawebsite-f6328f6fe19f.herokuapp.com"
  NEXT_PUBLIC_USE_MOCK = "0"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_BASE = "https://teawebsite-f6328f6fe19f.herokuapp.com"
  NEXT_PUBLIC_USE_MOCK = "0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
